[package]
name = "ironlint-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "ironlint"
path = "src/main.rs"

[dependencies]
ironlint-core = { path = "../ironlint-core" }
ironlint-adapters = { path = "../ironlint-adapters" }
clap.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true

[target.'cfg(unix)'.dependencies]
nix = { version = "0.31.3", default-features = false, features = ["fs", "signal", "process"] }

[dev-dependencies]
assert_cmd.workspace = true
predicates.workspace = true
tempfile.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
insta.workspace = true
expectrl = "0.7"

[lints]
workspace = true
